name: build/deploy
on: push

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      matrix:
        service: [api, frontend]
    name: build ${{ matrix.service }}
    runs-on: ubuntu-latest
    steps:
      - name: setup buildx
        uses: docker/setup-buildx-action@v3
      - name: prepare build metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.service }}
      - name: checkout
        uses: actions/checkout@v4
      - name: login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push image
        uses: docker/build-push-action@v6
        id: build
        with:
          file: ${{ matrix.service }}/Dockerfile
          context: ${{ matrix.service }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=image-${{ matrix.service }}
          cache-to: type=gha,mode=max,scope=image-${{ matrix.service }}
          push: ${{ github.ref == 'refs/heads/main' }}
